services:
  sayuna:
    container_name: sayuna
    # image: poprostuwitold/sayuna:latest
    build:
      context: .
      target: production
    stdin_open: true
    tty: true
    env_file:
     - .env
    # environment:
    #   - BOT_TOKEN=
    #   - DEV_GUILD_ID=
    #   - OWNER_ID=
    #   - BOT_ID='Sayuna'
    #   - BOT_PREFIX='$$'
    #   - ACTIVITY_NAME=''
    #   - ACTIVITY_TYPE=''
    #   - SPOTIFY_CLIENT_ID=''
    #   - SPOTIFY_CLIENT_SECRET=''
    restart: unless-stopped