services:
  sayuna_dev:
    container_name: sayuna_dev
    build:
      context: .
      target: development
    stdin_open: true
    tty: true
    env_file:
      - .env
    volumes:
      - .:/app  # Mount the current directory as /app in the container
    restart: unless-stopped